import { logoParts, logoViewBox } from "@/lib/logo";

/* The Libra logo from its traced vector parts (lib/logo.ts, generated by scripts/logo.py).
   The letters and tagline take `currentColor` (navy on light grounds, white on navy); the swooshes stay lime.
   `parts` tags every shape with data-part so the preloader can assemble it piece by piece. */
export function Logo({ title = "Libra Speciality Chemicals", parts = false, className = "" }: { title?: string; parts?: boolean; className?: string }) {
  return <svg className={`logo ${className}`} viewBox={logoViewBox} role={title ? "img" : undefined} aria-label={title || undefined} aria-hidden={title ? undefined : true} focusable="false">
    {logoParts.map((p) => <path key={p.id} d={p.d} fill={p.fill === "lime" ? "var(--lime)" : "currentColor"} data-part={parts ? p.id : undefined} />)}
  </svg>;
}
